apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: golang-ex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golang-ex
    app.kubernetes.io/part-of: del-temp
  name: golang-exgmok
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: golang-ex
    weight: null
status: {}
