apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: golang-ex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golang-ex
    app.kubernetes.io/part-of: del-temp
  name: golang-ex
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: golang-ex
status:
  loadBalancer: {}
